### ISSUE TITLE
[特性建议]希望能将有序列表的序列号设置成onenote的形式

### ISSUE THREAD

**Issue by liuyuanphy** [Achuan-2/siyuan-themes-tsundoku-light#21]
主题作者您好，您的这个主题真的非常好用和美观，我学习效率都提升很多，感谢您的劳动和无私奉献！
emm有一个建议能否将序列号设置成onenote的形式。见：https://ld246.com/article/1645946318817

**Comment by Achuan-2** [comment]
你好，请问你有具体实现方法吗

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/156170738-6c964408-35f6-42ad-b449-a1a66daaa398.png)
暂时搞出来了，我先试用一段时间在看看效果
```css
/*  二级有序列表 */
div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]{
    counter-reset: o2;
}


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order {
    color:transparent;
}
div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order::before {
    content: counter(o2,decimal)")";
    counter-increment: o2;
    color:var(--b3-theme-on-surface);
    position: absolute;
    right:5px;

}
div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order:after {
    width: 25px;
    height: 24px;
}
/*  三级有序列表 */

div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]{
    counter-reset: o3;
}


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order {
    color:transparent;
}

div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order::before {
    content: counter(o3,upper-latin)".";
    counter-increment: o3;
    color:var(--b3-theme-on-surface);
    position: absolute;

}
div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order:after {
    width: 25px;
    height: 24px;
}
/* 四级有序列表 */


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]{
    counter-reset: o4;
}


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order {
    color:transparent;
}


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order::before {
    content: counter(o4,lower-latin)".";
    counter-increment: o4;
    color:var(--b3-theme-on-surface);
    position: absolute;

}
div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]>.protyle-action--order:after {
    width: 25px;
    height: 24px;
}
/* 五级有序列表 */


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]> .list[data-subtype="o"]{
    counter-reset: o4;
}


div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]> .list[data-subtype="o"]>.li[data-subtype="o"] >.protyle-action--order {
    color:transparent;
}
div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"]> .list[data-subtype="o"]>.li[data-subtype="o"] >.protyle-action--order:before{
    content: counter(o4,lower-alpha)")";
    counter-increment: o4;
    color:var(--b3-theme-on-surface);
    position: absolute;
}

div[data-subtype="o"][data-node-index].list > .li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]>.li[data-subtype="o"] > .list[data-subtype="o"]:after {
    width: 25px;
    height: 24px;
}
```
