### ISSUE TITLE
[特性建议] 能否取消 mark 样式的挖空效果

### ISSUE THREAD

**Issue by aobatu** [Achuan-2/siyuan-themes-tsundoku-light#3]
原先用ctrl+e高亮了很多文档中的关键信息，但是最新主题更新后，把关键信息变成了挖空效果，导致本来想突显的信息反而被隐藏了，造成了很大的反向效果，期望能恢复到原先的高亮样式。

**Comment by Achuan-2** [comment]
我是希望通过挖空来强迫自己回忆的，不需要这个效果可以把主题theme.css文件中，下面这段删除。至于要不要取消，我还需要考虑一下。如果要添加背景色高亮，其实思源是可以通过字体样式添加的。
```css
/* 修改高亮为挖空效果，但是预览模式关闭（毕竟需要导出） */
.protyle-wysiwyg mark{
    color: transparent;
    transition: all 0.5s ease-in-out;
}
.protyle-wysiwyg mark:hover{
    color: var(--b3-protyle-inline-mark-color);
    transition: all 0.5s ease-in-out;
}
```
