### ISSUE TITLE
钉住页签添加图标

### ISSUE THREAD

**Issue by Achuan-2** [Achuan-2/siyuan-themes-tsundoku-light#49]
```css
/* 钉住添加图标 */
.item.item--pin::before {
    content: "📌";
    position: absolute;
    top: 0px;
    right: 0px;
    width: 13px;
    font-size: 0.7em;
    opacity: 0.7;
}
```
